BEGIN;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS shadow_runs CASCADE;
DROP TABLE IF EXISTS eval_runs CASCADE;
DROP TABLE IF EXISTS eval_datasets CASCADE;
DROP TABLE IF EXISTS prompt_versions CASCADE;
DROP TABLE IF EXISTS prompt_templates CASCADE;
COMMIT;
