import type { CSSProperties } from "react";

// Custom syntax highlighting theme using Echo design tokens.
const echoTheme: Record<string, CSSProperties> = {
  'code[class*="language-"]': {
    color: "#f8fafc",
    fontSize: "0.8125rem",
    fontFamily: 'var(--font-ibm-plex-mono), "IBM Plex Mono", "JetBrains Mono", monospace',
    direction: "ltr",
    textAlign: "left",
    whiteSpace: "pre-wrap",
    wordSpacing: "normal",
    wordBreak: "break-all",
    lineHeight: "1.6",
    tabSize: "2",
    hyphens: "none",
  },
  'pre[class*="language-"]': {
    color: "#f8fafc",
    fontSize: "0.8125rem",
    fontFamily: 'var(--font-ibm-plex-mono), "IBM Plex Mono", "JetBrains Mono", monospace',
    direction: "ltr",
    textAlign: "left",
    whiteSpace: "pre-wrap",
    wordSpacing: "normal",
    wordBreak: "break-all",
    lineHeight: "1.6",
    tabSize: "2",
    hyphens: "none",
    margin: 0,
    padding: "1rem 1.25rem",
    overflow: "auto",
  },
  comment: { color: "#94a3b8", fontStyle: "italic" },
  prolog: { color: "#94a3b8" },
  doctype: { color: "#94a3b8" },
  cdata: { color: "#94a3b8" },
  punctuation: { color: "#cbd5e1" },
  "attr-equals": { color: "#cbd5e1" },
  namespace: { opacity: "0.7" },
  property: { color: "#60a5fa" },
  tag: { color: "#60a5fa" },
  boolean: { color: "#f59e0b" },
  number: { color: "#f59e0b" },
  constant: { color: "#f59e0b" },
  symbol: { color: "#f59e0b" },
  deleted: { color: "#f87171" },
  selector: { color: "#34d399" },
  "attr-name": { color: "#38bdf8" },
  string: { color: "#34d399" },
  char: { color: "#34d399" },
  builtin: { color: "#c084fc" },
  inserted: { color: "#34d399" },
  operator: { color: "#e2e8f0" },
  entity: { color: "#60a5fa" },
  url: { color: "#60a5fa" },
  atrule: { color: "#c084fc" },
  "attr-value": { color: "#34d399" },
  keyword: { color: "#c084fc" },
  "keyword.module": { color: "#a78bfa" },
  "keyword.control-flow": { color: "#a78bfa" },
  function: { color: "#93c5fd" },
  "function.maybe-class-name": { color: "#93c5fd" },
  regex: { color: "#fb7185" },
  important: { color: "#f59e0b", fontWeight: "bold" },
  variable: { color: "#f8fafc" },
  parameter: { color: "#38bdf8" },
  "class-name": { color: "#fbbf24" },
  "maybe-class-name": { color: "#fbbf24" },
  interpolation: { color: "#60a5fa" },
  "interpolation-punctuation": { color: "#60a5fa" },
  italic: { fontStyle: "italic" },
  "tag.punctuation": { color: "#94a3b8" },
  "attr-value.punctuation": { color: "#34d399" },
};

export default echoTheme;
