// Package msg centralizes every log message and slog attribute key/value
// emitted across the codebase so the same key strings are never retyped.
package msg

const (
	ComponentKey = "component"

	ComponentServer        = "server"
	ComponentSeed          = "seed"
	ComponentConfig        = "config"
	ComponentDatabase      = "database"
	ComponentLifecycle     = "lifecycle"
	ComponentChat          = "chat"
	ComponentHistory       = "history"
	ComponentTokens        = "tokens"
	ComponentAutoTitle     = "auto-title"
	ComponentConsolidation = "consolidation"
	ComponentMemory        = "memory"
	ComponentStrategy      = "strategy"
	ComponentSettings      = "settings"
	ComponentFeatures      = "features"
	ComponentModel         = "model"
	ComponentLLMOps        = "llmops"
	ComponentAuth          = "auth"
)

const (
	KeyErr            = "err"
	KeySessionID      = "session_id"
	KeyUserID         = "user_id"
	KeyID             = "id"
	KeyBatchStart     = "batch_start"
	KeySessions       = "sessions"
	KeyPanic          = "panic"
	KeyPanicType      = "panic_type"
	KeyStack          = "stack"
	KeyMsgID          = "msg_id"
	KeyKey            = "key"
	KeyMessages       = "messages"
	KeyStatus         = "status"
	KeyPort           = "port"
	KeyReason         = "reason"
	KeyFrom           = "from"
	KeyInterval       = "interval"
	KeyEmail          = "email"
	KeyBody           = "body"
	KeyTurn           = "turn"
	KeyAction         = "action"
	KeyProvider       = "provider"
	KeyTenantID       = "tenant_id"
	KeyHint           = "hint"
	KeyContent        = "content"
	KeyTotal          = "total"
	KeyIncluded       = "included"
	KeyTokens         = "tokens"
	KeyTitle          = "title"
	KeySkipThreshold  = "skip_threshold"
	KeyUpToTurn       = "up_to_turn"
	KeyElapsed        = "elapsed"
	KeyTo             = "to"
	KeyTokenCount     = "token_count"
	KeyChoices        = "choices"
	KeyNewSummaryLen  = "new_summary_len"
	KeyKeepTurns      = "keep_turns"
	KeyContentLen     = "content_len"
	KeyMaxTurn        = "max_turn"
	KeyCutoffDays     = "cutoff_days"
	KeyPromptTemplate = "prompt_template"
	KeyFeatures       = "features"
)

const (
	MsgNoEnvFile = "No .env file found, using system environment variables"
	// MsgNoEnvFileDev is the lowercase variant historically emitted by the
	// database helper binaries (seed, migrate); the API server logs the
	// capitalized MsgNoEnvFile. Kept byte-identical to preserve CLI output.
	MsgNoEnvFileDev        = "no .env file found, using system environment variables"
	ErrServerStartup       = "Failed to start server"
	ErrRefuseToStart       = "refusing to start"
	WarnDBAutoMigration    = "database auto-migration error"
	ErrPanicRecovered      = "panic recovered"
	MsgServerStarting      = "server starting"
	MsgInternalServerError = "Internal Server Error"
	WarnEncryptionKeyEmpty = "%s is empty; API key encryption will fail at runtime"
)

const (
	ErrDatabaseURLNotSet         = "%s not set or database pool initialization failed"
	ErrAdminPasswordRequired     = "%s environment variable is required to seed the admin user"
	ErrLoadTestInProduction      = "refusing --load-test with %s=production: it TRUNCATES all sessions and messages. Development only."
	ErrLoadTestAborted           = "aborted: --load-test requires explicit 'yes' confirmation"
	MsgSkipIntegrationTest       = "%s not set, skipping integration test"
	ErrCheckExistingUser         = "failed to check existing user"
	InfoUserAlreadyExists        = "user already exists, using existing id"
	ErrHashPassword              = "failed to hash password"
	ErrSeedAdminUser             = "failed to seed admin user"
	InfoSeededDefaultAdmin       = "seeded default admin user"
	InfoSafeModeSkip             = "safe mode: skipping database truncation and fake load-test data seeding"
	InfoDatabaseSeeded           = "database seeded successfully with default admin user"
	InfoCleanupSessions          = "cleaning up old sessions and messages"
	ErrTruncateSessions          = "failed to truncate sessions table"
	InfoSessionsTruncated        = "old sessions and messages truncated successfully"
	InfoLoadTestSeedingDone      = "load-test seeding complete"
	InfoSeedingStress            = "seeding stress session with 10 turns (20 messages), ~4.4 MB (~1.1M tokens) per message"
	ErrCreateStressSession       = "failed to create stress session"
	ErrBeginTxStress             = "failed to begin transaction for stress messages"
	ErrCopyStressMessages        = "failed to copy stress messages"
	ErrCommitStressMessages      = "failed to commit stress messages"
	InfoStressSessionReady       = "stress test session ready"
	InfoPreparingBulk            = "preparing to seed 50 sessions and 1,000 realistic long-format messages"
	ErrGenerateUUIDs             = "failed to generate UUIDs for batch"
	ErrBeginTransaction          = "failed to begin transaction"
	ErrCopySessionsBatch         = "failed to copy sessions in batch"
	ErrCopyMessagesBatch         = "failed to copy messages in batch"
	ErrCommitTransaction         = "failed to commit transaction in batch"
	InfoCommittedBatch           = "committed batch"
	InfoDatabaseSeededFull       = "database seeded"
	WarnAgentTokenizeUnreachable = "agent tokenize unreachable, falling back to estimate"
	WarnAgentTokenizeFailed      = "agent tokenize failed, falling back to estimate"
	WarnAgentTokenizeDecode      = "agent tokenize decode failed, falling back to estimate"
	ErrMigrationFailed           = "migration failed"
	InfoMigrationCompleted       = "database migration completed successfully"
)

const (
	MsgPostgresConnected = "Connected to PostgreSQL successfully"
	ErrPostgresConfig    = "unable to parse database config"
	ErrPostgresPool      = "unable to create connection pool"
	ErrPostgresPing      = "unable to ping database"
	InfoRedisInitialized = "redis connection initialized"

	InfoNoPGSkipMigration     = "no PostgreSQL connection, skipping migration"
	ErrCreateLLMOpsTables     = "failed to create llmops studio tables"
	ErrCreateFeaturesTable    = "failed to create features table"
	InfoCreatedAPIKeysTable   = "created api_keys table"
	ErrAddStrategyVersionCol  = "failed to add strategy_version column to sessions"
	ErrAddTierCol             = "failed to add tier column to users"
	ErrAddLastAccessedCol     = "failed to add last_accessed_at column to sessions"
	ErrCreateIdxLastAccessed  = "failed to create idx_sessions_last_accessed"
	ErrCreateAppSettingsTable = "failed to create app_settings table"
	ErrAddStepsCol            = "failed to add steps column to messages"
	ErrAddStatusCol           = "failed to add status column to messages"
	ErrCreateIdxMsgStatus     = "failed to create idx_messages_session_status"
	ErrAddProviderTypeCol     = "failed to add provider_type column to user_preferences"
	ErrAddAPIKeyCol           = "failed to add api_key column to user_preferences"
	ErrAddBaseURLCol          = "failed to add base_url column to user_preferences"
	ErrAddHarnessTogglesCol   = "failed to add harness_toggles column to user_preferences"
	ErrCreateVectorExtension  = "failed to create vector extension"
	WarnPGVectorUnavailable   = "pgvector not available, creating memory_semantic without embedding"
	InfoMigrationNoVector     = "database migration completed (without pgvector)"
	InfoMigrationWithVector   = "database migration completed with pgvector & llmops studio support"
)

const (
	InfoWorkerStarted            = "worker started"
	InfoWorkerShuttingDown       = "worker shutting down"
	ErrCyclePanicRecovered       = "cycle panic recovered"
	WarnCycleSkipped             = "cycle skipped"
	InfoStartingMaintenanceCycle = "starting maintenance cycle"
	InfoMaintenanceCycleDone     = "maintenance cycle completed"
	ErrConsolidationScan         = "consolidation scan error"
	WarnSkipSessionProviderCfg   = "skip session: provider config resolution failed"
	InfoConsolidatingIdleSession = "consolidating idle session"
	ErrConsolidationFailed       = "consolidation failed"
	ErrDeprecatedScan            = "deprecated scan error"
	InfoEvaluatedStage1Decay     = "evaluated stage-1 decay"
	ErrArchiveScan               = "archive scan error"
	InfoArchivedInactiveSessions = "archived inactive sessions"
	ErrGCError                   = "gc error"
	InfoGCDeletedMessages        = "gc deleted messages"
	ErrRefreshStrategyRollout    = "failed to refresh strategy rollout cache"
	InfoRefreshedStrategyRollout = "refreshed strategy rollout cache"
)

const (
	WarnChatLockUnavailable      = "distributed session lock unavailable"
	WarnChatResolvePromptTmpl    = "failed to resolve prompt template name"
	InfoChatTurnStarted          = "chat turn started"
	ErrChatMarshalAgentPayload   = "failed to marshal agent payload"
	ErrChatFinalizeInterrupted   = "failed to finalize interrupted turn"
	ErrChatCreateAgentRequest    = "failed to create agent request"
	ErrChatAgentServiceDown      = "agent service unreachable"
	ErrChatReadAgentErrorResp    = "failed to read agent error response"
	InfoChatHistoryCapped        = "session history capped"
	ErrChatReadAgentResponse     = "failed to read agent response"
	InfoChatInterruptRequested   = "interrupt requested, notifying agent"
	ErrChatAgentCancelCall       = "agent cancel call failed"
	WarnChatStaleInterrupt       = "stale interrupt skipped"
	ErrChatReleaseSessionLock    = "failed to release session lock"
	ErrChatRenewSessionLock      = "failed to renew session lock"
	WarnChatLoadSettingsFallback = "failed to load settings, falling back to defaults"
	WarnChatSettingsNilFallback  = "settings returned nil, falling back to defaults"
	InfoConsolidationThreshold   = "token threshold reached, compacting session"
	ErrConsolidationAuto         = "error during auto-consolidation"
	ErrChatReloadAfterConsolid   = "failed to reload session after consolidation"
	ErrChatPinStrategyVersion    = "failed to pin strategy version"
	ErrChatTouchSession          = "failed to touch session"
	ErrChatPrepareTurn           = "failed to prepare turn"
	WarnChatCacheSkillsRedis     = "failed to cache skills in redis"
	ErrChatFlushGoroutinePanic   = "flush goroutine panic recovered"
	ErrChatFlushAfterRetries     = "flush error after retries"
	ErrChatClientWrite           = "client write failed"
	ErrChatClientFlush           = "client flush failed"
	ErrChatAgentStreamAborted    = "agent stream aborted"
	WarnChatFlushGoroutineLeft   = "flush goroutine did not exit; proceeding to finalize"
	ErrChatFinalizeTurn          = "error finalizing turn"
	InfoChatTurnCompleted        = "completed turn"
	WarnTokensAgentUnreachable   = "agent tokenize unreachable, falling back to estimate"
	WarnTokensAgentFailed        = "agent tokenize failed, falling back to estimate"
	WarnTokensAgentDecodeFailed  = "agent tokenize decode failed, falling back to estimate"
)

const (
	ErrMemoryStoreSemanticEmbed = "failed to store semantic memory with embedding, retrying without vector"
	WarnMemoryParseSemanticMeta = "failed to parse metadata for semantic memory"
	WarnMemoryParseProcedMeta   = "failed to parse metadata for procedural memory"
	ErrMemorySetEpisodicTTL     = "failed to set ttl for episodic key"
)

const (
	ErrTitleHTTPRequest         = "http request failed"
	ErrTitleReadErrorResponse   = "failed to read error response"
	WarnTitleProviderNon200     = "provider returned non-200 status"
	ErrTitleParseCompletion     = "failed to parse chat completion"
	DebugTitleFullBody          = "full response body"
	ErrTitleParseJSON           = "failed to parse json"
	DebugTitleContentAfterRegex = "content after regex"
	InfoTitleGenerated          = "generated title"
)

const (
	WarnStrategyRolloutCatalog     = "failed to load rollout percentages, returning catalog without them"
	WarnStrategyRolloutDefaults    = "failed to load rollout percentages, resolving with defaults"
	InfoConsolidationSkipThreshold = "session exceeds skip threshold, skipping consolidation"
	InfoConsolidationTokensExceed  = "skipping consolidation: tokens exceed skip threshold"
	InfoConsolidationBelowKeep     = "session max turn below keep turns, skipping pruning"
	InfoConsolidationPayloadCapped = "summarize payload capped"
	InfoConsolidationSummarizing   = "summarizing messages"
	InfoConsolidationPruned        = "pruning successful"
	ErrAimodelFetchModels          = "failed to fetch models"
	ErrLLMOpsInvalidateCache       = "failed to invalidate prompt cache key"
	WarnSettingsParsePromptTmpl    = "failed to parse prompt_template_name app setting"
	ErrSettingsDecryptAPIKey       = "failed to decrypt api key"
	WarnSettingsQueryPromptTmpl    = "failed to query latest active prompt template"
	WarnFeaturesCacheRedis         = "failed to cache implemented features in redis"
	WarnFeaturesLoadActiveSkip     = "failed to load active features, skipping validation"
	WarnFeaturesLoadImplSkip       = "failed to load implemented features, skipping validation"
	ErrLLMOpsPromoteRollback       = "promote version rollback failed"
	ErrLLMOpsRollbackTx            = "rollback version tx rollback failed"
)

const (
	ErrMissingToken = "Unauthorized: Missing token"
)

const (
	ErrAuthLogin    = "auth login failed"
	ErrAuthRegister = "auth register failed"
)

// HTTP response messages for the auth handler's internal-error paths.
const (
	MsgAuthLoginFailed    = "Login failed"
	MsgAuthRegisterFailed = "Failed to register"
)

const (
	// HTTP response messages emitted by the auth middleware stack. The generic
	// missing-token case reuses ErrMissingToken above.
	ErrInsufficientRole      = "Forbidden: insufficient role"
	ErrInvalidToken          = "Unauthorized: Invalid token"
	ErrInvalidAPICredentials = "Unauthorized: Invalid credentials"
	ErrAPIKeyRevoked         = "Unauthorized: API key is revoked"
	ErrMissingInternalToken  = "Unauthorized: Missing internal token"
	ErrInvalidInternalToken  = "Unauthorized: Invalid internal token"
	ErrInvalidTokenClaims    = "Unauthorized: Invalid token claims"
	ErrInvalidTokenSubject   = "Forbidden: Invalid token subject"
)

const (
	ErrAdminListKeys     = "Failed to list keys"
	ErrAdminNameRequired = "name is required"
	ErrAdminGenerateKey  = "Failed to generate key"
	ErrAdminStoreKey     = "Failed to store key"
	ErrAdminIDRequired   = "id is required"
	ErrAdminFindKey      = "Failed to find key"
	ErrAdminKeyNotFound  = "Key not found"
	ErrAdminRevokeKey    = "Failed to revoke key"
	MsgAdminKeyRevoked   = "Key revoked"
	ErrAdminGetStats     = "Failed to get stats"
)
