import type { CSSProperties } from "react";

// Custom syntax highlighting theme using Echo design tokens.
const echoTheme: Record<string, CSSProperties> = {
  'code[class*="language-"]': {
    color: "#e6edf3",
    fontSize: "0.835rem",
    fontFamily: 'var(--font-ibm-plex-mono), "IBM Plex Mono", "JetBrains Mono", monospace',
    direction: "ltr",
    textAlign: "left",
    whiteSpace: "pre-wrap",
    wordSpacing: "normal",
    wordBreak: "break-word",
    lineHeight: "1.6",
    tabSize: "2",
    hyphens: "none",
    background: "transparent",
  },
  'pre[class*="language-"]': {
    color: "#e6edf3",
    fontSize: "0.835rem",
    fontFamily: 'var(--font-ibm-plex-mono), "IBM Plex Mono", "JetBrains Mono", monospace',
    direction: "ltr",
    textAlign: "left",
    whiteSpace: "pre-wrap",
    wordSpacing: "normal",
    wordBreak: "break-word",
    lineHeight: "1.6",
    tabSize: "2",
    hyphens: "none",
    margin: 0,
    padding: "1rem 1.25rem",
    overflow: "auto",
    background: "transparent",
  },
  comment: { color: "#8b949e", fontStyle: "italic", background: "transparent" },
  prolog: { color: "#8b949e", background: "transparent" },
  doctype: { color: "#8b949e", background: "transparent" },
  cdata: { color: "#8b949e", background: "transparent" },
  punctuation: { color: "#8b949e", background: "transparent" },
  "attr-equals": { color: "#8b949e", background: "transparent" },
  namespace: { opacity: "0.7", background: "transparent" },
  property: { color: "#79c0ff", background: "transparent" },
  tag: { color: "#7ee787", background: "transparent" },
  boolean: { color: "#ff7b72", background: "transparent" },
  number: { color: "#79c0ff", background: "transparent" },
  constant: { color: "#79c0ff", background: "transparent" },
  symbol: { color: "#79c0ff", background: "transparent" },
  deleted: { color: "#ffa657", background: "transparent" },
  selector: { color: "#7ee787", background: "transparent" },
  "attr-name": { color: "#79c0ff", background: "transparent" },
  string: { color: "#a5d6ff", background: "transparent" },
  char: { color: "#a5d6ff", background: "transparent" },
  builtin: { color: "#ffa657", background: "transparent" },
  inserted: { color: "#7ee787", background: "transparent" },
  operator: { color: "#ff7b72", background: "transparent" },
  entity: { color: "#79c0ff", background: "transparent" },
  url: { color: "#79c0ff", background: "transparent" },
  atrule: { color: "#ff7b72", background: "transparent" },
  "attr-value": { color: "#a5d6ff", background: "transparent" },
  keyword: { color: "#ff7b72", fontWeight: "600", background: "transparent" },
  "keyword.module": { color: "#ff7b72", background: "transparent" },
  "keyword.control-flow": { color: "#ff7b72", background: "transparent" },
  function: { color: "#d2a8ff", background: "transparent" },
  "function.maybe-class-name": { color: "#d2a8ff", background: "transparent" },
  regex: { color: "#a5d6ff", background: "transparent" },
  important: { color: "#ff7b72", fontWeight: "bold", background: "transparent" },
  variable: { color: "#ffa657", background: "transparent" },
  parameter: { color: "#ffa657", background: "transparent" },
  "class-name": { color: "#ffa657", fontWeight: "600", background: "transparent" },
  "maybe-class-name": { color: "#ffa657", background: "transparent" },
  interpolation: { color: "#79c0ff", background: "transparent" },
  "interpolation-punctuation": { color: "#79c0ff", background: "transparent" },
  italic: { fontStyle: "italic", background: "transparent" },
  "tag.punctuation": { color: "#8b949e", background: "transparent" },
  "attr-value.punctuation": { color: "#a5d6ff", background: "transparent" },
};

export default echoTheme;
